.travis.yml, Gemfile, Gemfile.lock, app/app.rb, app/utils.rb/render_pdf.rb, app/utils/render_pdf.rb, test/fixtures/order_customer_address.json, test/render_pdf_test.rb, views/receipt/email.liquid
POS orders appear to not have a billing address the way web orders do. They do still have a customer default address though. This PR makes 2 changes:
* use `customer` `first_name` and `last_name` instead of `billing_address` `first_name` and `last_name` in the email template
* For the pdf fall back to customer default address if there is no billing address
* In light of these changes I removed a check that enforced the requirement of the billing address
=> Pos orders fix

src/app.rb, views/components/_email_modals.erb, views/components/_test_email.erb, views/home.erb
This simplifies a lot of code and the user experience. Before it was complicated exactly what was previewed. Now whatever is persisted is what is used to preview which makes the most sense.
=> make test email a top level feature.

Gemfile, Gemfile.lock, config/pagination.rb, src/app.rb, src/utils/render_pdf.rb, views/_donations.erb, views/_products.erb, views/_tabs.erb, views/home.erb
This PR adds a donations view. The UI is updated to have tabs for both products and donations.
I added pagination (for both products and donations) since it will be required for donations. I did this via `kaminari-sinatra` which adds the `padrino-helpers` gem (padrino is a framework built on top of sinatra which adds a lot the things most people use all the time). This caused some issues at first which I tracked down to `padrino-helpers` adding `partials` and `content_for` which I had manually added from `sinatra-contrib` and elsewhere. I was able to remove these extras and just rely on the padrino helpers.
The kaminari include also brought in `action-view` which caused issued with [wicked-pdf](https://github.com/mileszs/wicked_pdf) since it detected `Rails.env` and started trying to do …
=> Donations view

src/app.rb, src/models/charity.rb, src/models/donation.rb, src/utils/donation_service.rb, src/utils/render_pdf.rb, test/app_test.rb, test/render_pdf_test.rb
Before the templates can be updated to use the Donation model instead of Order directly (thus encapsulating access logic and simplifying templates, #37) the donation object needs to be passed in. This is necessary to avoid crashes and race conditions during the template migration.
=> pass donation model into templates

db/migrate/20180511143119_add_order_number.rb, db/migrate/20180511143155_backfill_order_number.rb, db/schema.rb, src/models/donation.rb, views/help.erb
A user needs the order_number included in the export. Because this field was delegated to order it wasn't included in the export. This PR adds a column and backfills it to denormalize the data for export.
Note to test locally I had to run with foreman to include ENV vars so that the attr_encrypted token on shop was able to be read:
```
foreman run bundle exec rake db:migrate 
```
This PR can be used as a template for the first step in adding a new field to donation for export
=> add order_number column and backfill

db/migrate/20180712131013_update_webhooks.rb, playbook.md, src/app.rb, src/concerns/install.rb
The webhook should be order/paid instead of create. Some orders are paid later and the tax receipt should not be sent until the payment is confirmed.
=> Order paid

Gemfile, Gemfile.lock, src/app.rb, test/app_test.rb, test/test_helper.rb, views/components/_pdf_modal.erb
closes #18
Makes preview_pdf into a proper form with POST so I can include a body of the current template. This means you don't have to save before previewing. It also lets me send other parameters to test other states, like VOID. This will be required as the PDF gets more states like updated, resent and refunded.
This makes use of smart data binding to use shadow forms that actually submit which are different than the form the user actually edits. This lets me have 2 forms on the same page without nesting them,
=> pass live edited template to preview method. add status to pdf preview

src/app.rb, src/models/donation.rb, views/help.erb, views/receipt/pdf.liquid
update template to use the order.created_at for donation received_at. created_at might not always match paid_at (which isn't a field) but this is better than it changing when the donation is re-issued. If a shop has a flow that runs into the case where paid_at != created_at a new field can be added to the donation that is copied forwards on update.
=> Recieved_at should not update if the receipt is re-issued

db/migrate/20190127071032_product_info.rb, db/schema.rb, src/app.rb, src/jobs/after_install_job.rb, src/jobs/product_webhook_job.rb, src/models/product.rb, src/routes/products.rb, src/tasks/backfill.rb, src/tasks/webhooks.rake, test/fixtures/product.json, test/products_test.rb, views/components/_product_picker.erb
Fixes a few small UI issues and inconvienves are products. Adds the full shopify product as a json column to the product model. This will enable showing more product information in the list. Webhooks are added to keep the data in sync.
After Ship:
* Backfill webhooks (rake recreate_webhooks)
* Backfill product data (rake backfill)
=> Product info and update

db/migrate/20181228050905_update_templates.rb, src/utils/email_service.rb, test/app_test.rb, views/components/_email_modals.erb, views/help.erb
If the email template includes an html closing tag `</html>` send it has body_html instead of body (aka html email vs plain text).
=> explore html email

public/announcement.txt
uses announcement process added in https://github.com/kevinhughes27/shopify-tax-receipts/pull/61
run with:
heroku run bundle exec rake send_announcement | tee output.log
=> Feature Announcement

db/migrate/20191111234127_add_donation_number.rb, db/schema.rb, src/jobs/order_webhook_job.rb, src/models/donation.rb, src/tasks/backfill.rake, test/donation_test.rb, test/order_refund_test.rb
This adds a donation number which is an incrementing ID starting at 1 for each shop. This is useful for charities' accounting tasks.
Part 1:
* add the column and model validation
* add the before_create logic to set the donation number
* modify the order update logic to not trip on a new donation number (even though donation number is not usable in liquid and may never be
*  backfill the number for each shop
When this ships new donations will be created but their numbers will be wrong until the backfill is ran. This is fine because this data is not presented anywhere yet.
Next:
* confirm the backfill
* add not null on donation_number
* add unique index
* include in csv export
This PR also includes 2 fixes to the refund handler. partial refunds can be handled the exact same as order …
=> Donation number

src/models/donation.rb, views/help.erb
adds the dontation number to the liquid drop and updates the documentation.
The donation number backend was added in: https://github.com/kevinhughes27/shopify-tax-receipts/pull/110 including the logic to ensure the receipt updates function with this new field.
In some ways it probably makes more sense for the donation number to be used instead of the ID in the default templates. Making changes to the default template is safe because when I calculate the pdf diff the old and new pdf are both re-rendered meaning the template change does not affect it (where if the pdfs were stored this would not be the case).
However changing to use donation_number would add the `Donation: 1` problem which is underiserable. Then I would also need to pick a default for the prefix similar to Shopify order …
=> add donation number to liquid

Gemfile.lock
Reverts kevinhughes27/shopify-tax-receipts#123
seems to have caused https://app.bugsnag.com/taxreceipts/taxreceipts/errors/5e00eed4d257200018f849ec?event_id=5e00eed40054c36be90f0000&i=em&m=nw
=> Revert "Bump sidekiq from 6.0.3 to 6.0.4"

db/migrate/20200105191330_add_discounts_setting.rb, db/schema.rb, playbook.md, src/jobs/order_webhook_job.rb, src/routes/charity.rb, test/fixtures/order_with_discount.json, test/order_test.rb, views/_charity.erb
Adds a setting to have the app subtract discounts from the donation amount.
With the box ticked the `total_discount` amount for a line item is subtracted from the `total` before the donation percentage is applied.
=> Subtract Discounts Setting

src/jobs/order_webhook_job.rb, test/order_test.rb
It seems Shopify does not always set `total_discount` and discount_allocations are a better way to get the discount applied to a line item.
This field is an empty array when there are no discounts (the code is safe here regardless).
=> use discount allocations

Gemfile, Gemfile.lock, playbook.md, src/app.rb, src/jobs/after_install_job.rb, src/jobs/job.rb, src/models/donation.rb, src/tasks/announcement.rake, src/tasks/debug.rake, src/tasks/webhooks.rake, test/support/helpers.rb
shopify-sinatra-app now supports setting an api version. This app involves sidekiq and setting up api sessions in a few other ways so I set a new constant for the api version which can be used everywhere and passed into shopify-sinatra-app.
ToDo
=> configure api version with a constant

views/components/_pdf_modal.erb
I had to remove the `target=+blank` from preview pdf form because it was erroring with 403 forbidden. I am not sure exactly when this broken, it could have been the secure cookie changes or it could be changes in new browsers. Either way it doesn't seem like a great idea.
It does make the workflow less great though because preview doesn't save the template and now the preview is in the same tab and when you go back you've lost your place (the edit state is actually there but you have to go back to the form to save it).
The ideal solution would be to send the preview request via javascript and render the preview side by side with the editor.
I also noticed that the preview on the html emails breaks the modal scroll and buttons are hidden afterwards. Side by side previews would be a good …
=> Fix pdf preview

Gemfile, Gemfile.lock, src/utils/render_pdf.rb
wkhtmltopdf_heroku does have support for the next heroku stack. It will need to be updated when I bump the stack.
Tested on staging:
=> bump wkhtmltopdf and wicked_pdf

src/models/charity.rb, test/charity_test.rb
the previous email regex only accepted a single email address. Now the function supports a comma separated list. Pony already support a comma separated list of emails to the `bcc` which is where this gets used https://github.com/benprew/pony/blob/master/spec/pony_spec.rb#L70
=> allow multiple emails in email_bcc

src/jobs/order_webhook_job.rb, test/order_test.rb
This is possible with certain discount configurations. Before discounts were added the check on number of products was sufficient to guard this.
=> don't create a donation if the amount is 0 or less
